const express = require("express")
const mongoose = require("mongoose")
const jwt = require("jsonwebtoken")
mongoose.connect("mongodb://localhost/offer")
const app = express()
const offerRoutes = require("./routes/offer")
const playerRoutes = require("./routes/playerlogin")
app.use("/offers", offerRoutes)
app.use("/", playerRoutes)
app.listen(5000, () => console.log("The server is up at 5000"))